import { Step1, Step2, Step3, Step4, Step5 } from './components/formSteps'
import DeklaracjaPDFGenerator from './components/DeklaracjaPDFGenerator'
import { FormType } from '@prisma/client'

export const deklaracjaFormConfig = {
	formType: FormType.DEKLARACJA_CZLONKOWSKA,
	sessionCookieName: 'formSession_deklaracja',
	defaultValues: {
		companyName: '',
		nip: '',
		regon: '',
		address: '',
		correspondenceAddress: '',
		phones: '',
		invoiceEmail: '',
		email: '',
		website: '',
		ceoName: '',
		authorizedPersons: '',
		registrationData: '',
		ownershipForm: '',
		employmentSize: '',
		transportLicense: '',
		iso9002Certificate: '',
		insuranceOC: '',
		businessDescription: '',
		transportMorski: false,
		transportKolejowy: false,
		transportLotniczy: false,
		logistyka: false,
		transportDrogowy: false,
		taborWlasny: false,
		taborObcy: false,
		transportInne: false,
		magazynWlasny: false,
		magazynObcy: false,
		organizacjaPrzewozow: false,
		agencjeCelne: false,
		krajowaSiec: '',
		zagranicznaSSiec: '',
		inneFormy: '',
		organizacje: '',
		rekomendacje: '',
		declarationStatute: false,
		signatoryName: '',
		signatoryPosition: '',
	},
	testData: {
		companyName: 'TestLogistics Sp. z o.o.',
		nip: '1234567890',
		regon: '123456789',
		address: 'ul. Testowa 123, 00-001 Warszawa',
		correspondenceAddress: 'ul. Testowa 123, 00-001 Warszawa',
		phones: '+48 123 456 789, +48 987 654 321',
		invoiceEmail: 'faktury@testlogistics.pl',
		email: 'kontakt@testlogistics.pl',
		website: 'https://testlogistics.pl',
		ceoName: 'Jan Kowalski',
		authorizedPersons: 'Anna Nowak - Dyrektor ds. Handlowych, Piotr Wiśniewski - Zastępca Dyrektora',
		registrationData: 'Data rejestracji: 15.03.2020, Sąd Rejonowy dla m.st. Warszawy, KRS: 0000123456',
		ownershipForm: 'Spółka z ograniczoną odpowiedzialnością',
		employmentSize: '25-50 pracowników',
		transportLicense: 'Tak, licencja nr TR/2020/001234 ważna do 31.12.2025',
		iso9002Certificate: 'Tak, certyfikat ISO 9001:2015 nr PL/ISO/2021/001',
		insuranceOC: 'Tak, PZU S.A., polisa nr 123456789, suma ubezpieczenia: 1.000.000 PLN',
		businessDescription:
			'Kompleksowe usługi logistyczne obejmujące transport krajowy i międzynarodowy, magazynowanie oraz dystrybucję towarów.',
		transportMorski: false,
		transportKolejowy: true,
		transportLotniczy: false,
		logistyka: true,
		transportDrogowy: true,
		taborWlasny: true,
		taborObcy: true,
		transportInne: false,
		magazynWlasny: true,
		magazynObcy: false,
		organizacjaPrzewozow: true,
		agencjeCelne: true,
		krajowaSiec: '3 oddziały (Warszawa, Kraków, Gdańsk)',
		zagranicznaSSiec: '2 firmy własne w Niemczech / 15 korespondentów w Europie',
		inneFormy: 'Współpraca z brokerami transportowymi, platformy cyfrowe (TimoCom, Trans.eu)',
		organizacje: 'Zrzeszenie Międzynarodowych Przewoźników Drogowych w Polsce (od 2020)',
		rekomendacje: 'LogiMax Sp. z o.o., TransEuropa S.A.',
		declarationStatute: true,
		signatoryName: 'Jan Kowalski',
		signatoryPosition: 'Prezes Zarządu',
	},
	steps: [Step1, Step2, Step3, Step4, Step5],
	PDFGeneratorComponent: DeklaracjaPDFGenerator,
}
